import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import genreWeeklyPopular from '@/utils/books/genreWeeklyPopular'
import { WeeklyPopular } from '@/components/WeeklyPopular'
import Info from '@/components/Info'

const inter = Inter({ subsets: ['latin'] })

export async function getServerSideProps() {
  const weeklyPopulars = await genreWeeklyPopular()

  // console.log({weeklyPopulars});
  
  return {
    props: {
      weeklyPopulars
    }
  }
}

export type weeklyPopulars = {
  book_id: number,
  cover: string,
  name: string,
  url: string
}

type PropsType = {
  weeklyPopulars: weeklyPopulars[]
}

export default function Home({ weeklyPopulars }: PropsType) {
  // console.log({weeklyPopulars})
  return (
    <>
      <Head>
        <title>Books App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        weeklyPopulars.length > 0 ? <WeeklyPopular weeklyPopulars={weeklyPopulars} /> : <Info />
      }
      
  
    </>
  )
}
